### ISSUE TITLE
Cannot build from project file

### ISSUE THREAD

**Issue by youkaicountry** [youkaicountry/yknyttlib#2]
YKnyttLib.csproj didn't update with the new files

@up-left how are you building this, and also how are you including it in the Godot project on your system? I have been vendoring in the built .dll of this, but I have noticed that I need to rebuild it on my end when you make changes here.

**Comment by youkaicountry** [comment]
Okay, I fixed it. Also had to add a reference to the `System.ValueTuple` library.

**Comment by up-left** [comment]
I cannot compile this because I don't have .Net 4.5 installed, and don't have YUtil.BinaryTools. So I just have added library files to the main project, and synchronize them with the library.
Also I think tuples is not so necessary here, can replace them with out variables..

**Comment by youkaicountry** [comment]
Ah, I see. I guess I am using a personal library I haven't published! Okay, I will take the time to publish that soon

**Comment by youkaicountry** [comment]
It might be best to actually just add this repo as a git submodule to the main game at some point
